_QUOTE_FORCED = "“forced”"


def _correctly_ignores(what):
    out_parts = [
        f"BHQ silently ignores the faint possible {what}.",
        " Or it ignores the manuscript entirely and simply supplies the consensus pointing here,",
        f" which has no {what}.",
        " It is hard to distinguish whether BHQ has done the right thing here by accident or on purpose.",
    ]
    return "".join(out_parts)


_COMMENT_1604 = [
    "Though it is not relevant to the point at hand, which is the presence of a מקף,",
    " note that in the LC, the shape we take to be מחפך is touching the bottom of the ל (lamed).",
]

_COMMENT_2125 = [
    "The dot is suspiciously brown rather than black,",
    " making me wonder whether the ו was pointed at all.",
]

_COMMENT_2221 = [
    "BHL Appendix A fails to note the anomalous non-pointing of the ל in the next word, ושלם.",
    " Nonethless I have included ושלם above.",
    " The letters of both words are re-inked, and as usual, the re-inking is sloppy.",
    " Perhaps some super-faint remains of an אתנח under ל can be seen.",
    " The top dot of the שווא (under the ש) is super-faint.",
    " I (charitably) transcribed it based on consensus expectations.",
    " A dot under the מ of עמו is fairly clear.",
    " It is (charitably) not transcribed by BHL, presumably based on consensus expectations.",
]

_COMMENT_2421 = [
    "Perhaps there is some super-faint evidence of a third dot that would make a סגול,",
    " but this could be just wishful thinking.",
    " Note that there is a third dot above the two clearer dots,",
    " but I take that to be part of the ע that did not flake off like its neighboring ink did.",
]

_COMMENT_2702 = [
    "Perhaps there is some super-faint evidence of a מקף that was ignored during re-inking.",
    " By the way, the evidence for the דחי on the א of the next word is super-faint.",
]

_COMMENT_2919 = [
    "Probably the ascender of the ל on the line below",
    f" {_QUOTE_FORCED} the סילוק to be early.",
]

_COMMENT_3629 = [
    "The color image strongly suggests that the mark in question is not ink.",
    " A געיה right next to סילוק like that would be extraordinary, BTW,",
    " though I feel no appeal to expectations is needed to dismiss this possible געיה.",
]

_COMMENT_3902 = [
    "The mark in question is very heavy,",
    " having a stroke width more typical of a letter-stroke than of a niqqud-stroke.",
    " Its clarity suggests it is part of the re-inking.",
    " Indeed perhaps it is only part of the re-inking,",
    " i.e. perhaps it reflects no mark (or only a much smaller mark) in the original.",
    " The mark in question may be two marks,",
    " a רביע (expected) overlaid with a גרש (unexpected).",
    " Or, it may be only a single mark whose lower end is, for some reason, a blob.",
]

_COMMENT_3913 = [
    "A more charitable interpretation of the image is that the רביע is present",
    " but is merged with the masorah circle.",
    " (It is fairly clear that a masorah circle is present.)",
    " Note that the vertical line above the ר is a סילוק from the line above.",
]

_BHQ_COMMENT_0914_AND_0930 = [
    "BHQ silently supplies the סילוק that is the consensus expectation,",
    " despite little or no manuscript evidence for it.",
]

_BHQ_COMMENT_4125 = [
    "BHQ silently supplies the סילוק that is the consensus expectation,",
    " despite no manuscript evidence for it.",
]

_BHQ_COMMENT_1203 = [
    "BHQ silently supplies the מקף that is the consensus expectation,",
    " despite no manuscript evidence for it.",
]

_BHQ_COMMENT_2702 = [
    "BHQ silently supplies the מקף that is the consensus expectation,",
    " despite little or no manuscript evidence for it.",
]

_BHQ_COMMENT_1804 = [
    "BHQ silently ignores the possible שווא part of the possible חטף פתח.",
    " It also silently ignores the possible intepretation of that ink as a געיה.",
    " I.e. other than the prepositive דחי accent,",
    " BHQ supplies only the (full) פתח that is the consensus expectation here.",
    " BHQ does so silently, i.e. with no note.",
]

_BHQ_COMMENT_1806 = [
    "BHQ positions the mark ambiguously.",
    " The mark is a little to the right of center.",
    " So it is not centered, as one would expect a טרחא to be,",
    " but neither is it as far to the right as דחי normally is in BHQ.",
]

_BHQ_COMMENT_2125 = [
    "BHQ silently supplies the שווא that is the consensus expectation,",
    " despite little or no manuscript evidence for it.",
]

_BHQ_COMMENT_2221 = [
    "BHQ transcribes these words as shown above.",
    " I.e. BHQ transcribes עמו as BHL does, and BHQ transcribes ושלם as I do.",
    " As is its habit, BHQ does all this silently,",
    " i.e. without any acknowledgement of",
    " uncertainties in transcription or",
    " departures from consensus expectations.",
]

_BHQ_COMMENT_2228 = [
    "BHQ places the mark a little left of center.",
    " Though this placement is odd,",
    " this makes it clear that a טרחא was intended rather than a דחי.",
]

_BHQ_COMMENT_2421 = [
    "BHQ silently supplies the סגול that is the consensus expectation.",
    " I.e. based on little or no manuscript evidence,",
    " BHQ silently infers a third dot centered below the two clearer dots.",
]

_BHQ_COMMENT_2808_AND_2911 = [
    "BHQ silently supplies the חיריק that is the consensus expectation,",
    " despite no manuscript evidence for it.",
]

_BHQ_COMMENT_3107 = [
    "BHQ reflects neither the manuscript nor the consensus expectation here.",
    " It reflects the manuscript except it places the סילוק under the א.",
    " This not only contradicts the manuscript,",
    " but also makes no sense given the רפה on the א.",
    " One might argue that this רפה should have been shown,",
    " despite the general policy of BHQ to ignore manuscript רפה marks.",
    " Regardless of whether the רפה should have been shown,",
    " its presence in the manuscript should have excluded the possibility of",
    " a סילוק under its letter (א)!",
]

_V_THEN_A = [
    "BHQ silently supplies the marks in the vowel-then-accent order that is",
    " the consensus expectation, in clear contradiction of the manuscript here.",
    " In my opinion BHQ shows itself to be out of date by continuing to aspire,",
    " as BHS did,",
    " to reflect all such ordering anomalies.",
    " I think the modern consensus is that these orderings are as meaningless as",
    " the variable length of ascenders on ל.",
    " Nonetheless, since BHQ still aspires to get these orderings right,",
    " it is fair for me to point out when it fails to do so."
]
_BHQ_COMMENT_1604 = [
    "Though it is not relevant to the point at hand,",
    " note that BHQ continues to fail to distinguish",
    " between גלגל and אתנח הפוך."
]
RECORDS = [
    {
        "bhla-i": 1,
        "cv": "1:21",
        "bhla-q": "",
        "bhla": "שָׁ֔מָה",
        "what-is-weird": "מ has no דגש",
        "mam": "שָׁ֔מָּה",
        "comment": "",
        "highlight": 2,
        "lcloc": {"page": "397B", "column": 1, "line": 1},
        "img": "0121.png",
    },
    {
        "bhla-i": 2,
        "cv": "4:9",
        "bhla-q": "",
        "bhla": "אֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱל֣וֹהַּ",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "398A", "column": 1, "line": -2},
        "img": "0409.png",
    },
    {
        "bhla-i": 3,
        "cv": "4:17",
        "bhla-q": "",
        "bhla": "מֵאֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "מֵאֱל֣וֹהַּ",
        "comment": "",
        "highlight": 5,
        "lcloc": {"page": "398A", "column": 2, "line": 10},
        "img": "0417.png",
    },
    {
        "bhla-i": 4,
        "cv": "7:1",
        "bhla-q": "",
        "bhla": "וְכִימֵ֖֗י",
        "what-is-weird": "רביע fights טרחא",
        "mam": "וְכִימֵ֖י",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "399A", "column": 1, "line": 4},
        "img": "0701.png",
        "bhq-comment": "BHQ silently ignores the possible רביע.",
    },
    {
        "bhla-i": 5,
        "cv": "7:9",
        "bhla-q": "",
        "bhla": "יַעֲלֽ͏ֶה׃",
        "what-is-weird": "סילוק precedes סגול",
        "mam": "יַעֲלֶֽה׃",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "399A", "column": 1, "line": 14},
        "img": "0709.png",
    },
    {
        "bhla-i": 6,
        "cv": "7:21",
        "bhla-q": "",
        "bhla": "וְשִׁ֖חֲרְתַּ֣נִי",
        "what-is-weird": "פתח on ח is חטף",
        "mam": "וְשִׁ֖חַרְתַּ֣נִי",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "399A", "column": 2, "line": 3},
        "img": "0721.png",
    },
    {
        "bhla-i": 7,
        "cv": "8:1",
        "bhla-q": "",
        "bhla": "וַיֹאמַֽר׃",
        "what-is-weird": "י (yod) has no דגש",
        "mam": "וַיֹּאמַֽר׃",
        "comment": "",
        "highlight": 2,
        "lcloc": {"page": "399A", "column": 2, "line": 5, "including-blank-lines": 1},
        "img": "0801.png",
    },
    {
        "bhla-i": 8,
        "cv": "8:7",
        "bhla-q": "",
        "bhla": "וְּ֝אַחֲרִיתְךָ֗",
        "what-is-weird": "שורוק dot fights שווא",
        "mam": "וְ֝אַחֲרִֽיתְךָ֗",
        "comment": "The געיה difference is not important to us here.",
        "highlight": 1,
        "lcloc": {"page": "399A", "column": 2, "line": 13, "including-blank-lines": 1},
        "img": "0807.png",
        "bhq-comment": "BHQ silently ignores the possible שורוק dot.",
    },
    {
        "bhla-i": 9,
        "cv": "9:14",
        "bhla-q": "(?)",
        "bhla": "עִמּוֹ׃",
        "what-is-weird": "סילוק may be missing",
        "mam": "עִמּֽוֹ׃",
        "comment": "",
        "highlight": 2,
        "lcloc": {"page": "399B", "column": 1, "line": 22, "including-blank-lines": 1},
        "img": "0914.png",
        "bhq-comment": "".join(_BHQ_COMMENT_0914_AND_0930),
    },
    {
        "bhla-i": 10,
        "cv": "9:30",
        "bhla-q": "(?)",
        "bhla": "כַּפָּי׃",
        "what-is-weird": "סילוק may be missing",
        "mam": "כַּפָּֽי׃",
        "comment": "",
        "highlight": 2,
        "lcloc": {"page": "399B", "column": 2, "line": 15},
        "img": "0930.png",
        "bhq-comment": "".join(_BHQ_COMMENT_0914_AND_0930),
    },
    {
        "bhla-i": 11,
        "cv": "9:35",
        "bhla-q": "",
        "bhla": "אַֽ֭דַבְּרָה",
        "what-is-weird": "פתח on א is not חטף",
        "mam": "אֲֽ֭דַבְּרָה",
        "comment": "",
        "highlight": 1,
        "lcloc": {"page": "399B", "column": 2, "line": -8},
        "img": "0935.png",
    },
    {
        "bhla-i": 12,
        "cv": "10:1",
        "bhla-q": "",
        "bhla": "אֲ֝דַבְּרָה֗",
        "what-is-weird": "רביע is on ה not ר",
        "mam": "אֲ֝דַבְּרָ֗ה",
        "comment": "",
        "highlight-bhla": 5,
        "highlight-mam": 4,
        "lcloc": {"page": "399B", "column": 2, "line": -6},
        "img": "1001.png",
    },
    {
        "bhla-i": 13,
        "cv": "10:15",
        "bhla-q": "",
        "bhla": "עָנְיֽ͏ִי׃",
        "what-is-weird": "סילוק precedes חיריק",
        "mam": "עׇנְיִֽי׃",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "400A", "column": 1, "line": 14},
        "img": "1015.png",
    },
    {
        "bhla-i": 14,
        "cv": "11:3",
        "bhla-q": "",
        "bhla": "יַחֲרִ֑ישׁו",
        "what-is-weird": "שורוק dot is missing",
        "mam": "יַחֲרִ֑ישׁוּ",
        "comment": "",
        "highlight": 6,
        "lcloc": {"page": "400A", "column": 1, "line": -1},
        "img": "1103.png",
    },
    {
        "bhla-i": 15,
        "cv": "11:6",
        "bhla-q": "",
        "bhla": "אֱ֝ל֗וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱ֝ל֗וֹהַּ",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "400A", "column": 2, "line": 5},
        "img": "1106.png",
    },
    {
        "bhla-i": 16,
        "cv": "11:7",
        "bhla-q": "",
        "bhla": "אֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱל֣וֹהַּ",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "400A", "column": 2, "line": 6},
        "img": "1107.png",
    },
    {
        "bhla-i": 17,
        "cv": "12:3",
        "bhla-q": "",
        "bhla": "וְאֶת_",
        "what-is-weird": "מקף is missing",
        "mam": "וְאֶת־",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "400A", "column": 2, "line": -1},
        "img": "1203.png",
        "bhq-comment": "".join(_BHQ_COMMENT_1203),
    },
    {
        "bhla-i": 18,
        "cv": "14:9",
        "bhla-q": "",
        "bhla": "מֵרֵ֣יַּח",
        "what-is-weird": "י (yod) has דגש",
        "mam": "מֵרֵ֣יחַ",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "401A", "column": 1, "line": -9},
        "img": "1409.png",
        "bhq-comment": "BHQ silently ignores the possible דגש.",
    },
    {
        "bhla-i": 19,
        "cv": "15:8",
        "bhla-q": "",
        "bhla": "אֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱל֣וֹהַּ",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "401A", "column": 2, "line": -7},
        "img": "1508.png",
    },
    {
        "bhla-i": 20,
        "cv": "15:34",
        "bhla-q": "",
        "bhla": "שֹֽׁ֥חַד׃",
        "what-is-weird": "מרכא fights סילוק",
        "mam": "שֹֽׁחַד׃",
        "comment": "",
        "highlight": 1,
        "lcloc": {"page": "401B", "column": 1, "line": -3},
        "img": "1534.png",
        "bhq-comment": "BHQ silently ignores the possible מרכא.",
    },
    {
        "bhla-i": 21,
        "cv": "16:4",
        "bhla-q": "",
        "bhla": "ל֤וּ־",
        "what-is-weird": "מקף is present",
        "mam": "ל֤וּ_",
        "comment": "".join(_COMMENT_1604),
        "highlight": 2,
        "lcloc": {"page": "401B", "column": 2, "line": 3},
        "img": "1604.png",
        "bhq-comment": "".join(_BHQ_COMMENT_1604),
    },
    {
        "bhla-i": 22,
        "cv": "16:13",
        "bhla-q": "",
        "bhla": "מְרֵרָֽתִי׃",
        "what-is-weird": "סילוק is on 2nd ר not ת",
        "mam": "מְרֵרָתִֽי׃",
        "comment": "",
        "highlight-bhla": 3,
        "highlight-mam": 4,
        "lcloc": {"page": "401B", "column": 2, "line": -10},
        "img": "1613.png",
    },
    {
        "bhla-i": 23,
        "cv": "16:20",
        "bhla-q": "",
        "bhla": "אֱ֝ל֗וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱ֝ל֗וֹהַּ",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "401B", "column": 2, "line": -2},
        "img": "1620.png",
    },
    {
        "bhla-i": 24,
        "cv": "18:4",
        "bhla-q": "",
        "bhla": "הֲ֭לְמַּעַנְךָ",
        "what-is-weird": "פתח on ה is חטף",
        "mam": "הַֽ֭לְמַעַנְךָ",
        "comment": "The געיה difference is not important to us here.",
        "highlight": 1,
        "lcloc": {"page": "402A", "column": 1, "line": -4},
        "img": "1804.png",
        "bhq-comment": "".join(_BHQ_COMMENT_1804),
    },
    {
        "bhla-i": 25,
        "cv": "18:6",
        "bhla-q": "",
        "bhla": "א֖וֹר",
        "what-is-weird": "דחי is placed like a טרחא",
        "mam": "א֭וֹר",
        "comment": "",
        "highlight": 1,
        "lcloc": {"page": "402A", "column": 1, "line": -2},
        "img": "1806.png",
        "bhq-comment": "".join(_BHQ_COMMENT_1806),
    },
    {
        "bhla-i": 26,
        "cv": "19:5",
        "bhla-q": "(?)",
        "bhla": "חֶרְפָּתִּֽֿי",
        "what-is-weird": "דגש may fight with רפה",
        "mam": "חֶרְפָּתִֽי׃",
        "comment": "Color photos show דגש to be unlikely.",
        "highlight": 4,
        "lcloc": {"page": "402A", "column": 2, "line": -5},
        "img": "1905.png",
        "bhq-comment": "BHQ silently lets the faint possible דגש “win” over the clear רפה in the manuscript.",
    },
    {
        "bhla-i": 27,
        "cv": "19:16",
        "bhla-q": "(?)",
        "bhla": "קָּ֭רָאתִי",
        "what-is-weird": "ק may have דגש",
        "mam": "קָ֭רָאתִי",
        "comment": "The dot is suspiciously brown rather than black.",
        "highlight": 1,
        "lcloc": {"page": "402B", "column": 1, "line": 8},
        "img": "1916.png",
        "bhq-comment": "BHQ silently supplies the possible דגש.",
    },
    {
        "bhla-i": 28,
        "cv": "21:25",
        "bhla-q": "",
        "bhla": "וִלֹֽא־",
        "what-is-weird": "ו has חיריק not שווא",
        "mam": "וְלֹֽא־",
        "comment": "".join(_COMMENT_2125),
        "highlight": 1,
        "lcloc": {"page": "403A", "column": 2, "line": 13},
        "img": "2125.png",
        "bhq-comment": "".join(_BHQ_COMMENT_2125),
    },
    {
        "bhla-i": 29,
        "cv": "22:21",
        "bhla-q": "(?)",
        "bhla": "עִמּ֑וֹ וּשְׁלם",
        "what-is-weird": "אתנח and ∅ not מונח and קמץ־אתנח?",
        "mam": "עִמּ֣וֹ וּשְׁלָ֑ם",
        "comment": "".join(_COMMENT_2221),
        "highlight": [2, 6],
        "lcloc": {"page": "403B", "column": 1, "line": -6},
        "img": "2221.png",
        "bhq-comment": "".join(_BHQ_COMMENT_2221),
    },
    {
        "bhla-i": 30,
        "cv": "22:28",
        "bhla-q": "",
        "bhla": "א֖וֹמֶר",
        "what-is-weird": "דחי is placed like a טרחא",
        "mam": "אֹ֭מֶר",
        "comment": "The מלא/חסר spelling difference is not important to us here.",
        "highlight": 1,
        "lcloc": {"page": "403B", "column": 2, "line": 2},
        "img": "2228.png",
        "bhq-comment": "".join(_BHQ_COMMENT_2228),
    },
    {
        "bhla-i": 31,
        "cv": "24:21",
        "bhla-q": "(?)",
        "bhla": "רֹעֵ֣ה",
        "what-is-weird": "ע may have צירה not סגול",
        "mam": "רֹעֶ֣ה",
        "comment": "".join(_COMMENT_2421),
        "highlight": 2,
        "lcloc": {"page": "404A", "column": 2, "line": -2},
        "img": "2421.png",
        "bhq-comment": "".join(_BHQ_COMMENT_2421),
    },
    {
        "bhla-i": 32,
        "cv": "27:2",
        "bhla-q": "",
        "bhla": "חַי_",
        "what-is-weird": "מקף is missing",
        "mam": "חַי־",
        "comment": "".join(_COMMENT_2702),
        "highlight": 2,
        "lcloc": {"page": "404A", "column": 2, "line": -2},
        "img": "2702.png",
        "bhq-comment": "".join(_BHQ_COMMENT_2702),
    },
    {
        "bhla-i": 33,
        "cv": "28:8",
        "bhla-q": "",
        "bhla": "הִדְריכֻ֥הוּ",
        "what-is-weird": "חיריק is missing",
        "mam": "הִדְרִיכ֥וּהוּ",
        "comment": "The מלא/חסר spelling difference is not important to us here.",
        "highlight": 3,
        "lcloc": {"page": "404B", "column": 2, "line": 5},
        "img": "2808.png",
        "bhq-comment": "".join(_BHQ_COMMENT_2808_AND_2911),
    },
    {
        "bhla-i": 34,
        "cv": "29:11",
        "bhla-q": "",
        "bhla": "וְעַ֥ין",
        "what-is-weird": "חיריק is missing",
        "mam": "וְעַ֥יִן",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "405A", "column": 1, "line": -12},
        "img": "2911.png",
        "bhq-comment": "".join(_BHQ_COMMENT_2808_AND_2911),
    },
    {
        "bhla-i": 35,
        "cv": "29:19",
        "bhla-q": "",
        "bhla": "בִּקְצִירֽ͏ִי׃",
        "what-is-weird": "סילוק precedes חיריק",
        "mam": "בִּקְצִירִֽי׃",
        "comment": "".join(_COMMENT_2919),
        "highlight": 5,
        "lcloc": {"page": "405A", "column": 1, "line": -4},
        "img": "2919.png",
    },
    {
        "bhla-i": 36,
        "cv": "31:5",
        "bhla-q": "",
        "bhla": "רַגְלֽ͏ִי׃",
        "what-is-weird": "סילוק precedes חיריק",
        "mam": "רַגְלִֽי׃",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "405B", "column": 1, "line": -9, "including-blank-lines": 1},
        "img": "3105.png",
        "bhq-comment": "".join(_V_THEN_A),
    },
    {
        "bhla-i": 37,
        "cv": "31:7",
        "bhla-q": "",
        "bhla": "מֻאֿוּֽם׃",
        "what-is-weird": "קבוץ and סילוק not סילוק and ∅",
        "mam": "מֽאֿוּם׃",
        "comment": "",
        "highlight": [1, 3],
        "lcloc": {"page": "405B", "column": 1, "line": -6, "including-blank-lines": 1},
        "img": "3107.png",
        "bhq-comment": "".join(_BHQ_COMMENT_3107),
        "bhq": "מֻאֽוּם׃",
    },
    {
        "bhla-i": 38,
        "cv": "31:33",
        "bhla-q": "",
        "bhla": "עֲוֺֽנִי׃",
        "what-is-weird": "סילוק is on ו not נ",
        "mam": "עֲוֺנִֽי׃",
        "comment": "",
        "highlight-bhla": 2,
        "highlight-mam": 3,
        "lcloc": {"page": "405B", "column": 2, "line": -3},
        "img": "3133.png",
    },
    {
        "bhla-i": 39,
        "cv": "32:6",
        "bhla-q": "",
        "bhla": "יְשִׁישׁ֑‍ִים",
        "what-is-weird": "אתנח precedes חיריק",
        "mam": "יְשִׁישִׁ֑ים",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "406A", "column": 1, "line": -6},
        "img": "3206.png",
        "bhq-comment": "".join(_V_THEN_A),
    },
    {
        "bhla-i": 40,
        "cv": "33:12",
        "bhla-q": "",
        "bhla": "אֱ֝ל֗וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱ֝ל֗וֹהַּ",
        "comment": "",
        "highlight": 4,
        "lcloc": {"page": "406B", "column": 1, "line": 2},
        "img": "3312.png",
    },
    {
        "bhla-i": 41,
        "cv": "33:30",
        "bhla-q": "",
        "bhla": "הַֽחַיִּים׃",
        "what-is-weird": "סילוק is on syl. 1 not 3",
        "mam": "הַחַיִּֽים׃",
        "comment": "",
        "highlight-bhla": 1,
        "highlight-mam": 3,
        "lcloc": {"page": "406B", "column": 1, "line": -1},
        "img": "3330.png",
    },
    {
        "bhla-i": 42,
        "cv": "34:19",
        "bhla-q": "",
        "bhla": "נִּכַּר־",
        "what-is-weird": "נ has דגש",
        "mam": "נִכַּר־",
        "comment": "The possible דגש is faint, especially compared with the adjacent דגש on כ.",
        "highlight": 1,
        "lcloc": {"page": "406B", "column": 2, "line": -2},
        "img": "3419.png",
        "bhq-comment": "".join(_correctly_ignores("דגש")),
    },
    {
        "bhla-i": 43,
        "cv": "36:29",
        "bhla-q": "",
        "bhla": "סֻכָּֽתֽוֹ׃",
        "what-is-weird": "כ has געיה",
        "mam": "סֻכָּתֽוֹ׃",
        "comment": "".join(_COMMENT_3629),
        "highlight": 2,
        "lcloc": {"page": "407B", "column": 1, "line": -5},
        "img": "3629.png",
        "bhq-comment": _correctly_ignores("געיה"),
    },
    {
        "bhla-i": 44,
        "cv": "37:6",
        "bhla-q": "",
        "bhla": "לַשֶּׁ֨לַג׀",
        "what-is-weird": "2nd ל has פתח not סגול",
        "mam": "לַשֶּׁ֨לֶג׀",
        "comment": "",
        "highlight": 3,
        "lcloc": {"page": "407B", "column": 2, "line": 7},
        "img": "3706.png",
    },
    {
        "bhla-i": 45,
        "cv": "38:12",
        "bhla-q": "",
        "bhla": "הְֽ֭מִיָּמֶיךָ",
        "what-is-weird": "simple שווא not חטף פתח",
        "mam": "הֲֽ֭מִיָּמֶיךָ",
        "comment": "39:20 is similar",
        "highlight": 1,
        "lcloc": {"page": "408A", "column": 1, "line": -12},
        "img": "3812.png",
    },
    {
        "bhla-i": 46,
        "cv": "39:2",
        "bhla-q": "",
        "bhla": "וְ֝יָדַעְתָּ֜",
        "what-is-weird": "גרש not רביע",
        "mam": "וְ֝יָדַעְתָּ֗",
        "comment": "".join(_COMMENT_3902),
        "highlight": 5,
        "lcloc": {"page": "408A", "column": 2, "line": -3},
        "img": "3902.png",
        "bhq-comment": "BHQ silently supplies the רביע that is the consensus expectation.",
    },
    {
        "bhla-i": 47,
        "cv": "39:6",
        "bhla-q": "",
        "bhla": "מְלֵֽחָה׃",
        "what-is-weird": "סילוק is on ל not ח",
        "mam": "מְלֵחָֽה׃",
        "comment": "",
        "highlight-bhla": 2,
        "highlight-mam": 3,
        "lcloc": {"page": "408B", "column": 1, "line": 3},
        "img": "3906.png",
    },
    {
        "bhla-i": 48,
        "cv": "39:13",
        "bhla-q": "(?)",
        "bhla": "אֶ֝בְרָה",
        "what-is-weird": "רביע מגרש may lack רביע",
        "mam": "אֶ֝בְרָ֗ה",
        "comment": "".join(_COMMENT_3913),
        "highlight": 3,
        "lcloc": {"page": "408B", "column": 1, "line": 11},
        "img": "3913.png",
        "bhq-comment": "BHQ seems to split the mark(s) in question into a רביע on ר and a masorah circle on ב.",
    },
    {
        "bhla-i": 49,
        "cv": "39:20",
        "bhla-q": "",
        "bhla": "הְֽ֭תַרְעִישֶׁנּוּ",
        "what-is-weird": "simple שווא not חטף פתח",
        "mam": "הֲֽ֭תַרְעִישֶׁנּוּ",
        "comment": "38:12 is similar",
        "highlight": 1,
        "lcloc": {"page": "408B", "column": 1, "line": -10},
        "img": "3920.png",
    },
    {
        "bhla-i": 50,
        "cv": "40:10",
        "bhla-q": "(?)",
        "bhla": "גָֽא֣וֹן",
        "what-is-weird": "געיה may be present (on ג)",
        "mam": "גָא֣וֹן",
        "comment": "The mark in question could easily be accidental.",
        "highlight": 1,
        "lcloc": {"page": "408B", "column": 2, "line": -11},
        "img": "4010.png",
    },
    {
        "bhla-i": 51,
        "cv": "40:26",
        "bhla-q": "",
        "bhla": "לֶֽחֱיוֹ׃",
        "what-is-weird": "סילוק on ל not י (yod)",
        "mam": "לֶחֱיֽוֹ׃",
        "comment": "",
        "highlight-bhla": 1,
        "highlight-mam": 3,
        "lcloc": {"page": "409A", "column": 1, "line": 8},
        "img": "4026.png",
    },
    {
        "bhla-i": 52,
        "cv": "41:25",
        "bhla-q": "",
        "bhla": "לִבְלִי־חָת׃",
        "what-is-weird": "סילוק missing",
        "mam": "לִבְלִי־חָֽת׃",
        "comment": "",
        "highlight": 5,
        "lcloc": {"page": "409A", "column": 2, "line": 14},
        "img": "4125.png",
        "bhq-comment": "".join(_BHQ_COMMENT_4125),
    },
]
