TABLE = [
    {
        "bhla-i": 1,
        "cv": "1:21",
        "bhla-q": "",
        "bhla": "שָׁ֔מָה",
        "what-is-weird": "מ has no דגש",
        "mam": "שָׁ֔מָּה",
        "comment": "",
        "highlight": 2,
    },
    {
        "bhla-i": 2,
        "cv": "4:9",
        "bhla-q": "",
        "bhla": "אֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱל֣וֹהַּ",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 3,
        "cv": "4:17",
        "bhla-q": "",
        "bhla": "מֵאֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "מֵאֱל֣וֹהַּ",
        "comment": "",
        "highlight": 5,
    },
    {
        "bhla-i": 4,
        "cv": "7:1",
        "bhla-q": "",
        "bhla": "וְכִימֵ֖֗י",
        "what-is-weird": "רביע fights טרחא",
        "mam": "וְכִימֵ֖י",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 5,
        "cv": "7:9",
        "bhla-q": "",
        "bhla": "יַעֲלֽ͏ֶה׃",
        "what-is-weird": "סילוק precedes סגול",
        "mam": "יַעֲלֶֽה׃",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 6,
        "cv": "7:21",
        "bhla-q": "",
        "bhla": "וְשִׁ֖חֲרְתַּ֣נִי",
        "what-is-weird": "פתח on ח is חטף",
        "mam": "וְשִׁ֖חַרְתַּ֣נִי",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 7,
        "cv": "8:1",
        "bhla-q": "",
        "bhla": "וַיֹאמַֽר׃",
        "what-is-weird": "י (yod) has no דגש",
        "mam": "וַיֹּאמַֽר׃",
        "comment": "",
        "highlight": 2,
    },
    {
        "bhla-i": 8,
        "cv": "8:7",
        "bhla-q": "",
        "bhla": "וְּ֝אַחֲרִיתְךָ֗",
        "what-is-weird": "שורוק dot fights שווא",
        "mam": "וְ֝אַחֲרִֽיתְךָ֗",
        "comment": "The געיה difference is not important to us here.",
        "highlight": 1,
    },
    {
        "bhla-i": 9,
        "cv": "9:14",
        "bhla-q": "(?)",
        "bhla": "עִמּוֹ׃",
        "what-is-weird": "סילוק is missing",
        "mam": "עִמּֽוֹ׃",
        "comment": "",
        "highlight": 2,
    },
    {
        "bhla-i": 10,
        "cv": "9:30",
        "bhla-q": "(?)",
        "bhla": "כַּפָּי׃",
        "what-is-weird": "סילוק is missing",
        "mam": "כַּפָּֽי׃",
        "comment": "",
        "highlight": 2,
    },
    {
        "bhla-i": 11,
        "cv": "9:35",
        "bhla-q": "",
        "bhla": "אַֽ֭דַבְּרָה",
        "what-is-weird": "פתח on א is not חטף",
        "mam": "אֲֽ֭דַבְּרָה",
        "comment": "",
        "highlight": 1,
    },
    {
        "bhla-i": 12,
        "cv": "10:1",
        "bhla-q": "",
        "bhla": "אֲ֝דַבְּרָה֗",
        "what-is-weird": "רביע is on ה not ר",
        "mam": "אֲ֝דַבְּרָ֗ה",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 13,
        "cv": "10:15",
        "bhla-q": "",
        "bhla": "עָנְיֽ͏ִי׃",
        "what-is-weird": "סילוק precedes חיריק",
        "mam": "עׇנְיִֽי׃",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 14,
        "cv": "11:3",
        "bhla-q": "",
        "bhla": "יַחֲרִ֑ישׁו",
        "what-is-weird": "שורוק dot is missing",
        "mam": "יַחֲרִ֑ישׁוּ",
        "comment": "",
        "highlight": 6,
    },
    {
        "bhla-i": 15,
        "cv": "11:6",
        "bhla-q": "",
        "bhla": "אֱ֝ל֗וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱ֝ל֗וֹהַּ",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 16,
        "cv": "11:7",
        "bhla-q": "",
        "bhla": "אֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱל֣וֹהַּ",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 17,
        "cv": "12:3",
        "bhla-q": "",
        "bhla": "וְאֶת_",
        "what-is-weird": "מקף is missing",
        "mam": "וְאֶת־",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 18,
        "cv": "14:9",
        "bhla-q": "",
        "bhla": "מֵרֵ֣יַּח",
        "what-is-weird": "י (yod) has דגש",
        "mam": "מֵרֵ֣יחַ",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 19,
        "cv": "15:8",
        "bhla-q": "",
        "bhla": "אֱל֣וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱל֣וֹהַּ",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 20,
        "cv": "15:34",
        "bhla-q": "",
        "bhla": "שֹֽׁ֥חַד׃",
        "what-is-weird": "מרכא fights סילוק",
        "mam": "שֹֽׁחַד׃",
        "comment": "",
        "highlight": 1,
    },
    {
        "bhla-i": 21,
        "cv": "16:4",
        "bhla-q": "",
        "bhla": "ל֤וּ־",
        "what-is-weird": "מקף is present",
        "mam": "ל֤וּ_",
        "comment": "",
        "highlight": 2,
    },
    {
        "bhla-i": 22,
        "cv": "16:13",
        "bhla-q": "",
        "bhla": "מְרֵרָֽתִי׃",
        "what-is-weird": "סילוק is on 2nd ר not ת",
        "mam": "מְרֵרָתִֽי׃",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 23,
        "cv": "16:20",
        "bhla-q": "",
        "bhla": "אֱ֝ל֗וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱ֝ל֗וֹהַּ",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 24,
        "cv": "18:4",
        "bhla-q": "",
        "bhla": "הֲ֭לְמַּעַנְךָ",
        "what-is-weird": "פתח on ח is חטף",
        "mam": "הַֽ֭לְמַעַנְךָ",
        "comment": "",
        "highlight": 1,
    },
    {
        "bhla-i": 25,
        "cv": "18:6",
        "bhla-q": "",
        "bhla": "א֖וֹר",
        "what-is-weird": "דחי is placed like a טרחא",
        "mam": "א֭וֹר",
        "comment": "",
        "highlight": 1,
    },
    {
        "bhla-i": 26,
        "cv": "19:5",
        "bhla-q": "(?)",
        "bhla": "חֶרְפָּתִּֽֿי",
        "what-is-weird": "דגש may fight with רפה",
        "mam": "חֶרְפָּתִֽי׃",
        "comment": "Color photos show דגש to be unlikely.",
        "highlight": 4,
    },
    {
        "bhla-i": 27,
        "cv": "19:16",
        "bhla-q": "(?)",
        "bhla": "קָּ֭רָאתִי",
        "what-is-weird": "ק may have דגש",
        "mam": "קָ֭רָאתִי",
        "comment": "",
        "highlight": 1,
    },
    {
        "bhla-i": 28,
        "cv": "21:25",
        "bhla-q": "",
        "bhla": "וִלֹֽא־",
        "what-is-weird": "ו has חיריק not שווא",
        "mam": "וְלֹֽא־",
        "comment": "",
        "highlight": 1,
},
    {
        "bhla-i": 29,
        "cv": "22:21",
        "bhla-q": "(?)",
        "bhla": "עִמּ֑וֹ וּשְׁלם",
        "what-is-weird": "אתנח and ∅ not מונח and קמץ־אתנח",
        "mam": "עִמּ֣וֹ וּשְׁלָ֑ם",
        "comment": "Typical sloppy re-inking. Perhaps some super-faint remains of the אתנח under ל can be seen. Various dots not mentioned are, based on consensus expectations, either generously transcribed despite having only super-faint remains or generously ignored despite being fairly clear.",
        "highlight": 2,
    },
    {
        "bhla-i": 30,
        "cv": "22:28",
        "bhla-q": "",
        "bhla": "א֖וֹמֶר",
        "what-is-weird": "דחי is placed like a טרחא",
        "mam": "אֹ֭מֶר",
        "comment": "The מלא/חסר spelling difference is not important to us here.",
        "highlight": 1,
    },
    {
        "bhla-i": 31,
        "cv": "24:21",
        "bhla-q": "(?)",
        "bhla": "רֹעֵ֣ה",
        "what-is-weird": "ע may have צירה not סגול",
        "mam": "רֹעֶ֣ה",
        "comment": "",
        "highlight": 2,
    },
    {
        "bhla-i": 32,
        "cv": "27:2",
        "bhla-q": "",
        "bhla": "חַי_",
        "what-is-weird": "מקף is missing",
        "mam": "חַי־",
        "comment": "",
        "highlight": 2,
    },
    {
        "bhla-i": 33,
        "cv": "28:8",
        "bhla-q": "",
        "bhla": "הִדְריכֻ֥הוּ",
        "what-is-weird": "חיריק is missing",
        "mam": "הִדְרִיכ֥וּהוּ",
        "comment": "The מלא/חסר spelling difference is not important to us here.",
        "highlight": 3,
    },
    {
        "bhla-i": 34,
        "cv": "29:11",
        "bhla-q": "",
        "bhla": "וְעַ֥ין",
        "what-is-weird": "חיריק is missing",
        "mam": "וְעַ֥יִן",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 35,
        "cv": "29:19",
        "bhla-q": "",
        "bhla": "בִּקְצִירֽ͏ִי׃",
        "what-is-weird": "סילוק precedes חיריק",
        "mam": "בִּקְצִירִֽי׃",
        "comment": "",
        "highlight": 5,
    },
    {
        "bhla-i": 36,
        "cv": "31:5",
        "bhla-q": "",
        "bhla": "רַגְלֽ͏ִי׃",
        "what-is-weird": "סילוק precedes חיריק",
        "mam": "רַגְלִֽי׃",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 37,
        "cv": "31:7",
        "bhla-q": "",
        "bhla": "מֻאֿוּֽם׃",
        "what-is-weird": "קבוץ and סילוק not סילוק and ∅",
        "mam": "מֽאֿוּם׃",
        "comment": "",
        "highlight": [1, 3],
    },
    {
        "bhla-i": 38,
        "cv": "31:33",
        "bhla-q": "",
        "bhla": "עֲוֺֽנִי׃",
        "what-is-weird": "סילוק is on ו not נ",
        "mam": "עֲוֺנִֽי׃",
        "comment": "",
        "highlight-bhla": 2,
        "highlight-mam": 3,
    },
    {
        "bhla-i": 39,
        "cv": "32:6",
        "bhla-q": "",
        "bhla": "יְשִׁישׁ֑‍ִים",
        "what-is-weird": "אתנח precedes חיריק",
        "mam": "יְשִׁישִׁ֑ים",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 40,
        "cv": "33:12",
        "bhla-q": "",
        "bhla": "אֱ֝ל֗וֹהַ",
        "what-is-weird": "ה has no מפיק",
        "mam": "אֱ֝ל֗וֹהַּ",
        "comment": "",
        "highlight": 4,
    },
    {
        "bhla-i": 41,
        "cv": "33:30",
        "bhla-q": "",
        "bhla": "הַֽחַיִּים׃",
        "what-is-weird": "סילוק is on syl. 1 not 3",
        "mam": "הַחַיִּֽים׃",
        "comment": "",
        "highlight-bhla": 1,
        "highlight-mam": 3,
    },
    {
        "bhla-i": 42,
        "cv": "34:19",
        "bhla-q": "",
        "bhla": "נִּכַּר־",
        "what-is-weird": "נ has דגש",
        "mam": "נִכַּר־",
        "comment": "",
        "highlight": 1,
    },
    {
        "bhla-i": 43,
        "cv": "36:29",
        "bhla-q": "",
        "bhla": "סֻכָּֽתֽוֹ׃",
        "what-is-weird": "כ has געיה",
        "mam": "סֻכָּתֽוֹ׃",
        "comment": "right next to סילוק!",
        "highlight": 2,
    },
    {
        "bhla-i": 44,
        "cv": "37:6",
        "bhla-q": "",
        "bhla": "לַשֶּׁ֨לַג׀",
        "what-is-weird": "2nd ל has פתח not סגול",
        "mam": "לַשֶּׁ֨לֶג׀",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 45,
        "cv": "38:12",
        "bhla-q": "",
        "bhla": "הְֽ֭מִיָּמֶיךָ",
        "what-is-weird": "simple שווא not חטף פתח",
        "mam": "הֲֽ֭מִיָּמֶיךָ",
        "comment": "39:20 is similar",
        "highlight": 1,
    },
    {
        "bhla-i": 46,
        "cv": "39:2",
        "bhla-q": "",
        "bhla": "וְ֝יָדַעְתָּ֜",
        "what-is-weird": "גרש not רביע",
        "mam": "וְ֝יָדַעְתָּ֗",
        "comment": "",
        "highlight": 5,
    },
    {
        "bhla-i": 47,
        "cv": "39:6",
        "bhla-q": "",
        "bhla": "מְלֵֽחָה׃",
        "what-is-weird": "סילוק is on ל not ח",
        "mam": "מְלֵחָֽה׃",
        "comment": "",
        "highlight-bhla": 2,
        "highlight-mam": 3,
    },
    {
        "bhla-i": 48,
        "cv": "39:13",
        "bhla-q": "(?)",
        "bhla": "אֶ֝בְרָה",
        "what-is-weird": "רביע מגרש without רביע",
        "mam": "אֶ֝בְרָ֗ה",
        "comment": "",
        "highlight": 3,
    },
    {
        "bhla-i": 49,
        "cv": "39:20",
        "bhla-q": "",
        "bhla": "הְֽ֭תַרְעִישֶׁנּוּ",
        "what-is-weird": "simple שווא not חטף פתח",
        "mam": "הֲֽ֭תַרְעִישֶׁנּוּ",
        "comment": "38:12 is similar",
        "highlight": 1,
    },
    {
        "bhla-i": 50,
        "cv": "40:10",
        "bhla-q": "(?)",
        "bhla": "גָֽא֣וֹן",
        "what-is-weird": "געיה on ג",
        "mam": "גָא֣וֹן",
        "comment": "right next to מונח!",
        "highlight": 1,
    },
    {
        "bhla-i": 51,
        "cv": "40:26",
        "bhla-q": "",
        "bhla": "לֶֽחֱיוֹ׃",
        "what-is-weird": "סילוק on ל not י (yod)",
        "mam": "לֶחֱיֽוֹ׃",
        "comment": "",
        "highlight-bhla": 1,
        "highlight-mam": 3,
    },
    {
        "bhla-i": 52,
        "cv": "41:25",
        "bhla-q": "",
        "bhla": "לִבְלִי־חָת׃",
        "what-is-weird": "סילוק missing",
        "mam": "לִבְלִי־חָֽת׃",
        "comment": "",
        "highlight": 5,
    },
]
